spring:
  cloud:
    azure:
      servicebus:
        connection-string: Endpoint=sb://galangservicebus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=jHA/zBiFj4JLOEvJygpPMUQWIqiKxRJnF+ASbKQQjdU=
        entity-type: queue
    function:
      definition: getUser
    stream:
      bindings:
        getUser-in-0:
          destination: galang-queue